<a href="https://colab.research.google.com/github/YasuharuSuzuki/23_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Section 15 NumPy配列
# Section 15-1 NumPy配列を作る(教科書P.344)

### NumPyとは
<img src="https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg">

- numpyは、大量の数値データに対して一気に高速な計算を行うことに特化した数値演算ライブラリです。
- リストでもfor文と組み合わせることで同様の演算を行うことができますが、numpyは内部処理がC言語で書かれており、非常に高速に効率よく処理を行うことが出来ます。

### NumPyを使うメリット
- パフォーマンス: numpyはC言語で書かれているため、Pythonのリストを使用するよりも計算が高速です。
- メモリ効率: numpy配列はPythonのリストに比べてメモリ効率が良く、大量の数値データを扱うのに適しています。
- 便利な数学関数: numpyには、統計、線形代数、フーリエ変換など、多くの便利な数学関数が組み込まれています。
- 配列操作: numpyは多次元配列をサポートしており、形状変更、スライシング、インデックス付けなどの便利な配列操作を提供します。
- ブロードキャスティング: numpyはブロードキャスティングをサポートしており、異なる形状の配列間での算術演算を可能にします。
- 互換性: numpyは多くの他のPythonライブラリ（pandas、matplotlib、scikit-learnなど）と互換性があり、データ分析のエコシステムの中心的な役割を果たしています。

### はじめてみよう
- 上記の利点により、numpyは科学計算やデータ分析において重要なツールとなっています。
- 今回の講義では、このNumPyを使った数値演算の基本について学んでいきましょう。

## 参考サイト
### [【Python早見表】16. NumPy (1): ベクトル](https://chokkan.github.io/python/16numpy1.html)
### [【Python早見表】17. NumPy (2): 行列・テンソル](https://chokkan.github.io/python/17numpy2.html)
### [【Python入門】5-3. NumPyライブラリ](https://utokyo-ipp.github.io/5/5-3.html)

## サンプルプログラム1　NumPy配列を作る

In [1]:
import numpy as np # NumPyモジュールを読み込む

In [2]:
# リストからNumPy配列を作る
x_list = [1, 2, 3, 4, 5]
x_np = np.array(x_list)
print(x_np)

[1 2 3 4 5]


In [3]:
# 型を確認する
type(x_np)

numpy.ndarray

### 要素の型を指定してNumPy配列を作る
- 要素の型をいくつか紹介
  - np.int32  整数型(32bit)。大量のデータを一気に処理する時には高速。除算が苦手。数値の範囲は±21億を扱える。
  - np.int64  整数型(64bit)。int32よりは若干処理時間がかかるものの高速。除算が苦手。int32より表現できる数値の範囲が広く、±900京を扱える。
  - np.float32  浮動小数点型(32bit)。精度は悪いが、高速に浮動小数点を使いたい時に使用。int32と同程度の速度で、除算は遅くない。
  - np.float64  浮動小数点型(64bit)。精度が高い科学技術計算をしたい時に使用。除算は遅くない。

In [4]:
# int32型でnp.array()を作成
x_int32 = np.array(x_list, dtype=np.int32)
print("x_int32=", x_int32, ", x_int32.dtype=", x_int32.dtype)

x_int32= [1 2 3 4 5] , x_int32.dtype= int32


In [5]:
# float64型でnp.array()を作成
x_float64 = np.array(x_list, dtype=np.float64)
print("x_float64=", x_float64, ", x_float64.dtype=", x_float64.dtype)

x_float64= [1. 2. 3. 4. 5.] , x_float64.dtype= float64


### 多次元配列
- リストと同様にNumPyも多次元配列を作ることができます。
- リストとの違い
  - ベクトル演算や行列演算が可能。ブロードキャストが出来る。
  - 高速で効率の良い処理ができる。

In [6]:
# 2次元配列
x_2x3 = [ # 2次元配列の構築
    [1,2,3],
    [4,5,6]
]
print("---- リスト ----")
print(x_2x3)
print("---- NumPy ----")
print(np.array(x_2x3)) 

---- リスト ----
[[1, 2, 3], [4, 5, 6]]
---- NumPy ----
[[1 2 3]
 [4 5 6]]


- 上記のように、リストと異なりNumPyの2次元配列は行列のように出力されます

In [7]:
# 3次元配列
x_3x2x3 = [ # 3次元配列の構築
    [[1,2,3],[ 4, 5, 6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]],
]
print("---- リスト ----")
print(x_3x2x3)
print("---- NumPy ----")
print(np.array(x_3x2x3)) 

---- リスト ----
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
---- NumPy ----
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


- 3次元配列は行列の配列のように出力されます

### reshape()を使ったndarrayの形状変更
- reshape()を使うと配列の形状を変更することが出来ます

In [8]:
# 3x2x3 の配列を2x9の配列に変更する
np.array(x_3x2x3).reshape(2,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [9]:
# 3x2x3 の配列を1x2x3x3の配列に変更する
np.array(x_3x2x3).reshape(1,2,3,3)

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]])

## 練習プログラム1　NumPy配列を作る(1.5点)
- NumPy配列を作ってみましょう
  - リストからNumPy配列を作ってみましょう。
  - 型を確認してみましょう。
  - 要素の型を指定してNumPy配列を作ってみましょう。
  - 多次元配列を作ってみまｓｙほう。
  - reshape()を使ってndarrayの形状変更してみましょう。
- このNotebookのサンプルプログラムや教科書の値とは違う独自の値を使いましょう。変数名も独自のものに変えましょう。

---
---
---
---
---

## サンプルプログラム2　配列の要素へのアクセス

#### 参照
- 配列の要素へのアクセスはリストと同じです
- マイナス値を使用すると配列の終端からアクセスできるのも同じです

In [10]:
x_np # 配列

array([1, 2, 3, 4, 5])

In [11]:
x_np[0] # 最初の要素

1

In [12]:
x_np[2] # 3番目の要素

3

In [13]:
x_np[-1] # 最後の要素

5

In [14]:
x_2x3 # 2x3行列

[[1, 2, 3], [4, 5, 6]]

In [15]:
x_2x3[-1][1] # 最後の行の2列目

5

In [16]:
x_3x2x3 # 3x2x3行列

[[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18]]]

In [17]:
x_3x2x3[2][0][1]

14

#### 代入
- リスト同様に代入していきます

In [18]:
x_np[1] = 99 # 最初の要素
x_np

array([ 1, 99,  3,  4,  5])

In [19]:
x_2x3[1][-1] = 9 # 2行目の最後の要素
x_2x3

[[1, 2, 3], [4, 5, 9]]

In [20]:
x_3x2x3[2][-1][-1] = 999
x_3x2x3

[[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 999]]]

#### スライス
- リストと同様にスライスも可能です

In [21]:
print(x_np[2:4])

[3 4]


- numpyのリストでは代入が出来ます

In [22]:
print(x_np)
x_np[1:4] = 8
print(x_np)

[ 1 99  3  4  5]
[1 8 8 8 5]


## 練習プログラム2　配列の要素へのアクセス(1.8点)
- 配列の要素へアクセスしてみましょう
  - NumPyの1次元配列から値を取り出してみましょう
  - NumPyの多次元配列から値を取り出してみましょう
  - NumPyの1次元配列に値をセットしてみましょう
  - NumPyの多次元配列に値をセットしてみましょう
  - NumPyの配列からスライスで値を取り出してみましょう。
  - NumPyの配列にスライスで値をセットしてみましょう。
- このNotebookのサンプルプログラムや教科書の値とは違う独自の値を使いましょう。変数名も独自のものに変えましょう。

---
---
---
---
---

## サンプルプログラム3　配列の演算
- NumPyで作成した配列はベクトルとして扱うことが出来、ベクトルの和、差や、スカラ値の演算が出来ます
- ここでは使用しませんが、画像処理でデファクトスタンダードであるOpenCVというライブラリを用いてNumPy配列として取り出した後、画像に直接演算を掛ける時によく使います。

#### ベクトルの演算
$
    \boldsymbol{x} =
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} \quad, 
    \boldsymbol{y} =
        \begin{pmatrix}
            10 \\
            6 \\
            2 \\
        \end{pmatrix} \quad
$

に対して、様々な演算を紹介する。

In [23]:
x = np.array([1, 3, 5])
y = np.array([10, 6, 2])

#### ベクトルの和
$
    \boldsymbol{x + y} =
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} +
        \begin{pmatrix}
            10 \\
            6 \\
            2 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1 + 10 \\
            3 + 6 \\
            5 + 2 \\
        \end{pmatrix} =
        \begin{pmatrix}
            11 \\
            9 \\
            7 \\
        \end{pmatrix}
$

In [24]:
x + y

array([11,  9,  7])

#### ベクトルの差
$
    \boldsymbol{x - y} =
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} -
        \begin{pmatrix}
            10 \\
            6 \\
            2 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1 - 10 \\
            3 - 6 \\
            5 - 2 \\
        \end{pmatrix} =
        \begin{pmatrix}
            -9 \\
            -3 \\
            3 \\
        \end{pmatrix}
$

In [25]:
x - y

array([-9, -3,  3])

#### スカラ値とベクトルの和
$
    \boldsymbol{1 + x} =
        \begin{pmatrix}
            1 \\
            1 \\
            1 \\
        \end{pmatrix} +
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} =
        \begin{pmatrix}
            2 \\
            4 \\
            6 \\
        \end{pmatrix}
$

In [26]:
1 + x

array([2, 4, 6])

#### スカラ値とベクトルの差
$
    \boldsymbol{1 - x} =
        \begin{pmatrix}
            1 \\
            1 \\
            1 \\
        \end{pmatrix} -
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} =
        \begin{pmatrix}
            0 \\
            -2 \\
            -4 \\
        \end{pmatrix}
$

In [27]:
1 - x

array([ 0, -2, -4])

#### スカラ値とベクトルの積
$
    \boldsymbol{3 * x} =
        \begin{pmatrix}
            3 \\
            3 \\
            3 \\
        \end{pmatrix} ⊙
        \begin{pmatrix}
            1 \\
            3 \\
            5 \\
        \end{pmatrix} =
        \begin{pmatrix}
            3 \times 1 \\
            3 \times 3 \\
            3 \times 5 \\
        \end{pmatrix} =
        \begin{pmatrix}
            3 \\
            9 \\
            15 \\
        \end{pmatrix}
$

In [28]:
3 * x

array([ 3,  9, 15])

#### sum(), max(), min(), mean(), var(), std(), sort()
- リストと組み込み関数でも用意されているこれらの処理はNumPyでも出来ます

In [29]:
(x + y).sum() # 合計

27

In [30]:
(x + y).max() # 最大

11

In [31]:
(x + y).min() # 最小

7

In [32]:
(x + y).mean() # 平均

9.0

In [33]:
(x + y).var() # 分散

2.6666666666666665

In [34]:
(x + y).std() # 標準偏差

1.632993161855452

In [35]:
np.sort(x - y) # 組み込み関数のnumpy.sort()。np.sortは昇順でソートされた新しい配列を返します。

array([-9, -3,  3])

In [36]:
a = x - y # NumPyオブジェクトのインスタンスメソッドのsort()。配列内のデータを直接昇順でソートします。データを直接書き換えるので注意。
a.sort()
a

array([-9, -3,  3])

#### 行列の演算
- ここでは、NumPyで行列について
- 画像処理のデファクトスタンダードであるOepnCVでは、画像データをNumPy行列で扱います。

$
    \boldsymbol{X} =
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix} \quad, 
    \boldsymbol{Y} =
        \begin{pmatrix}
            1 \quad 3 \quad 5 \\
            2 \quad 4 \quad 6 \\
        \end{pmatrix} \quad
$

に対して、様々な演算を紹介する。

In [37]:
x = np.array([
    [1, 2, 3],
    [2, 3, 4],
], dtype='float')
y = np.array([
    [1, 3, 5],
    [2, 4, 6],
], dtype='float')

#### 行列の和
$
    \boldsymbol{X+Y} =
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix} +
        \begin{pmatrix}
            1 \quad 3 \quad 5 \\
            2 \quad 4 \quad 6 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1+1 \quad 2+3 \quad 3+5 \\
            2+2 \quad 3+4 \quad 4+6 \\
        \end{pmatrix} =
        \begin{pmatrix}
            2 \quad 5 \quad 8 \\
            4 \quad 7 \quad 10 \\
        \end{pmatrix}
$

In [38]:
x + y

array([[ 2.,  5.,  8.],
       [ 4.,  7., 10.]])

#### 行列の差
$
    \boldsymbol{X-Y} =
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix} -
        \begin{pmatrix}
            1 \quad 3 \quad 5 \\
            2 \quad 4 \quad 6 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1-1 \quad 2-3 \quad 3-5 \\
            2-2 \quad 3-4 \quad 4-6 \\
        \end{pmatrix} =
        \begin{pmatrix}
            0 \quad -1 \quad -2 \\
            0 \quad -1 \quad -2 \\
        \end{pmatrix}
$

In [39]:
x - y

array([[ 0., -1., -2.],
       [ 0., -1., -2.]])

#### スカラ値と行列の和
$
    \boldsymbol{1+X} =
        \begin{pmatrix}
            1 \quad 1 \quad 1 \\
            1 \quad 1 \quad 1 \\
        \end{pmatrix} +
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1+1 \quad 1+2 \quad 1+3 \\
            1+2 \quad 1+3 \quad 1+4 \\
        \end{pmatrix} =
        \begin{pmatrix}
            2 \quad 3 \quad 4 \\
            3 \quad 4 \quad 5 \\
        \end{pmatrix}
$

In [40]:
1 + x

array([[2., 3., 4.],
       [3., 4., 5.]])

#### スカラ値と行列の差
$
    \boldsymbol{1-X} =
        \begin{pmatrix}
            1 \quad 1 \quad 1 \\
            1 \quad 1 \quad 1 \\
        \end{pmatrix} -
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix} =
        \begin{pmatrix}
            1-1 \quad 1-2 \quad 1-3 \\
            1-2 \quad 1-3 \quad 1-4 \\
        \end{pmatrix} =
        \begin{pmatrix}
            0 \quad -1 \quad -2 \\
            -1 \quad -2 \quad -3 \\
        \end{pmatrix}
$

In [41]:
1 - x

array([[ 0., -1., -2.],
       [-1., -2., -3.]])

#### 転置行列
$
    \boldsymbol{Z} =
        Y^T =
        \begin{pmatrix}
            1 \quad 3 \quad 5 \\
            2 \quad 4 \quad 6 \\
        \end{pmatrix}^T =
        \begin{pmatrix}
            1 \quad 2 \\
            3 \quad 4 \\
            5 \quad 6 \\
        \end{pmatrix}
$

In [42]:
z = y.T
z

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### 行列積
$
    \boldsymbol{XZ} =
        \begin{pmatrix}
            1 \quad 2 \quad 3 \\
            2 \quad 3 \quad 4 \\
        \end{pmatrix}
        \begin{pmatrix}
            1 \quad 2 \\
            3 \quad 4 \\
            5 \quad 6 \\
        \end{pmatrix} \\
        =
        \begin{pmatrix}
            1 \times 1 + 2 \times 3 + 3 \times 5 \quad 1 \times 2 + 2 \times 4 + 3 \times 6 \\
            2 \times 1 + 3 \times 3 + 4 \times 5 \quad 2 \times 2 + 3 \times 4 + 4 \times 6 \\
        \end{pmatrix}
        =
        \begin{pmatrix}
            22 \quad 28 \\
            31 \quad 40 \\
        \end{pmatrix}
$

In [43]:
np.dot(x, z)

array([[22., 28.],
       [31., 40.]])

In [44]:
# 行列積 は @ 演算子で書くこともできます。
x @ z

array([[22., 28.],
       [31., 40.]])

#### median(), argmin(), argmax()
- リストにはないNumPy特有のメソッドをいくつか紹介します
- NumPyは本当にたくさんの種類のメソッドがあるので

In [45]:
# 中央値。
# 平均値は異常値に引っ張られやすく、データの特性を掴むには中央値を使用した方が良いことが良くあります。
x = np.array([-3, -5,  0,  3, -5, -4, -1,  0,  1,  4])
np.median(x)

-0.5

In [46]:
# 最小値のインデックスを返す
# AIの開発において画像データからエッジを検出することがあるのですが、そういった場合にピクセルを1件1件チェックしていき、一番大きい画素値や一番小さい画素値を検索していくことがあります。
# そういった時に使用します。
# インデックスを返すことで、どこで最小値が得られたのかのピクセル座標を取得することが出来ます。
x.argmin()

1

In [47]:
# 最大値のインデックスを返す
x.argmax()

9

## 練習プログラム3　配列の演算(6.3点)
- 配列の演算を行ってみましょう
  - ベクトルの和
  - ベクトルの差
  - スカラ値とベクトルの和
  - スカラ値とベクトルの差
  - スカラ値とベクトルの積
  - sum()
  - max()
  - min()
  - mean()
  - var()
  - std()
  - sort()
  - 行列の和
  - 行列の差
  - スカラ値と行列の和
  - スカラ値と行列の差
  - 転置行列
  - 行列積
  - median()
  - argmin()
  - argmax()
- このNotebookのサンプルプログラムや教科書の値とは違う独自の値を使いましょう。変数名も独自のものに変えましょう。

---
---
---
---
---

## サンプルプログラム4　効率よく配列を作る
- NumPyには配列を作る関数がたくさんあります。
- 以下の関数を使って、配列を作ってみましょう
  - np.zeros()
  - np.zeros_like()
  - np.ones()
  - np.ones_like()
  - np.full()
  - np.full_like()
  - arrange()
  - linspace()
  - np.random.randint()

In [53]:
# ゼロ行列を作る
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
# xと同じ要素数のゼロ行列を作る
x = np.array([1, 2, 3])
np.zeros_like(x)

array([0, 0, 0])

In [55]:
# １ベクトルを作る
np.ones(4)

array([1., 1., 1., 1.])

In [56]:
# xと同じ要素数の1ベクトルを作る。
np.ones_like(x)

array([1, 1, 1])

In [57]:
# 任意の値で初期化したベクトル
np.full(4, -2.)

array([-2., -2., -2., -2.])

In [58]:
# xと同じ要素数で任意の値で初期化したベクトル。
np.full_like(x, -2.)

array([-2, -2, -2])

In [59]:
# 範囲を指定して初期化したベクトル
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# 範囲とステップを指定して初期化したベクトル
np.arange(1, 100, 20)

array([ 1, 21, 41, 61, 81])

In [61]:
# 始点と終点、分割数を指定してベクトルを作成
np.linspace(0, 360, 5)

array([  0.,  90., 180., 270., 360.])

In [62]:
# 始点と終点、分割数を指定してベクトルを作成。終端を含むかどうかをFalse
np.linspace(0, 360, 4, endpoint=False)

array([  0.,  90., 180., 270.])

In [65]:
# 一様分布の乱数の数列を作る
np.random.rand(10)

array([0.261097  , 0.35786319, 0.86341332, 0.32207028, 0.92262618,
       0.63276294, 0.36727232, 0.69294754, 0.71645561, 0.5978944 ])

In [66]:
# 標準正規分布の乱数の数列を作る
np.random.randn(10)

array([ 0.12193143,  0.65203865, -0.55957291,  1.24399463, -0.41809497,
       -0.62952325, -0.81496906, -1.27760337,  1.55010977,  0.97352371])

In [50]:
# 整数の乱数の数列を作る
np.random.randint(-5, +5, 10) # -5〜 +5の乱数の配列を、要素数10で作る。

array([ 0, -1,  4, -3, -2,  4, -4,  3, -5,  3])

---
---
---
---
---

## 練習プログラム4　配列の作成(1.8点)
- NumPyの関数を使って以下の配列を作る練習をしましょう。
  - ゼロ行列を作る
  - １行列を作る
  - 任意の値で初期化したベクトルを作る
  - 範囲を指定してベクトルを作る
  - 始点と終点、分割数を指定してベクトルを作る
  - 乱数の数列を作る
- このNotebookのサンプルプログラムや教科書の値とは違う独自の値を使いましょう。変数名も独自のものに変えましょう。